name: Coverage Pages
permissions:
  contents: read

on:
  push:
    branches: [ main ]

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install

      - run: npm run test:coverage --workspace=client

      - name: Upload coverage to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: client/coverage
          
  deploy:
    needs: coverage
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
     - uses: actions/deploy-pages@v4
